### ISSUE TITLE
Allow import-from-derivation

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#1]
IFD is currently not allowed. We could allow it, though probably with a less clean perspective on what will be built.

**Comment by jameshaydon** [comment]
+1

**Comment by jkarni** [comment]
This is fixed!

**Comment by jameshaydon** [comment]
Unfortunately it only works if my call to `flake-utils.lib.eachSystem [ "x86_64-linux" ]` **_only_** includes `"x86_64-linux"`, if I add `"x86_64-darwin"` I get an error:

```
error: a 'x86_64-darwin' with features {} is required to build...
```
