### ISSUE TITLE
Require a garnix.yaml file to be present before doing builds

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#10]
The current setup is somewhat annoying since:

1) Enabling builds in a repo is not entirely obvious - you have to dig a bit to find the app, and then to enable it.
2) You can't have branches that don't build.

Instead, we can require that the app be enabled, *and* a garnix.yaml file be present. That way you can enable the app on all repos when configuring.

**Comment by sellout** [comment]
Honestly, I love the zero-config bit, but I think it should at least only try to build if there’s a flake (and I guess we already talked about making garnix use a flake output a la `hydraJobs` instead of a separate config).

**Comment by jkarni** [comment]
This is done. Either a flake.nix or a garnix.yaml needs to be present in the branch, else all checks are skipped.
