### ISSUE TITLE
Make builds in public repos public

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#13]
The builds are public via github already anyhow.

**Comment by dit7ya** [comment]
Related question - If I have a private repo, I am not sure if the key https://garnix.io/docs/caching provides for substitution to me is specific to me or not?

**Comment by jkarni** [comment]
No, it's not. Currently the security model is just based on keeping the hash private. I'll add a note about that to the link.

Probably we should change that at some point, but hopefully the hash-as-password is serviceable in the short run
