### ISSUE TITLE
All builds are failing without any log

### ISSUE THREAD

**Issue by dit7ya** [garnix-io/issues#15]
Basically the title. I initially thought it is because of some configuration change I made recently. But it turns out the same is true for old commits which worked previously.

**Comment by jkarni** [comment]
Ooof. I checked and you're right. Though this only applies to `nixosConfigurations` (packages and checks are fine). Looking into it in a bit!

**Comment by jkarni** [comment]
This should be fixed - please check and confirm. Sorry about that!

**Comment by dit7ya** [comment]
Working again. Thanks!
