### ISSUE TITLE
Linux builder: CI's `nix build` fails, when it succeeds locally

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#23]
Repo it happens: https://github.com/srid/emanote-template

CI log: https://github.com/srid/emanote-template/runs/8058506408

<img width="493" alt="image" src="https://user-images.githubusercontent.com/3998/187080836-c6e09d39-4b08-4e91-8049-c58cf5a46d46.png">

`package default [x86_64-linux]` fails, but I can build it successfully on my local machine:

```
❯ nix build .#packages.x86_64-linux.default --json
warning: Using saved setting for 'extra-substituters = https://cache.garnix.io' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=' from ~/.local/share/nix/trusted-settings.json.
[{"drvPath":"/nix/store/qz9w433nmbir1wvx9f983lc72nkgx7mx-emanote-static-website.drv","outputs":{"out":"/nix/store/mn8bn1bs1c1pmm79rmyvgkkrnwifc12q-emanote-static-website"}}]

❯ nix --option sandbox true build .#packages.x86_64-linux.default --json
warning: Using saved setting for 'extra-substituters = https://cache.garnix.io' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=' from ~/.local/share/nix/trusted-settings.json.
[{"drvPath":"/nix/store/qz9w433nmbir1wvx9f983lc72nkgx7mx-emanote-static-website.drv","outputs":{"out":"/nix/store/mn8bn1bs1c1pmm79rmyvgkkrnwifc12q-emanote-static-website"}}]
```

Nix info,

```
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.11 (Raccoon), 22.11.20220721.a65b5b3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos-22.11pre392433.8f485713f5e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 - ```

**Comment by jkarni** [comment]
It seems like the server is doing the right thing - I don't really know why there's a difference in behavior. The garnix nix is on 2.5 - could you remove the failing package and emanote-static and try building with a 2.5?

**Comment by srid** [comment]
Turns out this was because the dependent package wasn't using an **explicit** nixpkgs input.

- I switched it to use an explicit nixpkgs https://github.com/EmaApps/emanote/commit/fcac63448b13c6c8c95aabc1d45fd659e5197f87
- And then updated emanote-template, which in turns uses the new nixpkgs https://github.com/srid/emanote-template/commit/0a695f579840cd4b84db1178d77060d84a2ac774

Here's the relevant part from the 2nd link:

```
• Updated input 'emanote/nixpkgs':
    'path:/nix/store/1ha33ma070pyxw5kkcx61qi7ypzzxzah-source?lastModified=1659077768&narHash=sha256-P0XIHBVty6WIuIrk2DZNvLcYev9956y1prT4zL212H8=&rev=2a93ea177c3d7700b934bf95adfe00c435f696b8' (2022-07-29)
  → 'github:nixos/nixpkgs/21de2b973f9fee595a7a1ac4693efff791245c34' (2022-09-02)
```

Interesting that the *default* nixpkgs inputs come from the local nix store. It seems like this is variable, and thus could explain the difference in behaviour. 

Moral of the story, I guess: always specify nixpkgs input explicitly in the flake.

---

This issue can be closed, I think. Maybe this "gotcha" can be mentioned somewhere in the documentation, however.

**Comment by srid** [comment]
The issue resurfaced https://github.com/srid/emanote-template/pull/19#issuecomment-1279988467

> Moral of the story, I guess: always specify nixpkgs input explicitly in the flake.

So, obviously, this is *not enough*. The input flake must be made a non-flake. https://github.com/EmaApps/emanote/commit/65dd75053674aaf4fc36c0ad689938c8d6158e2e ... and then it works! https://github.com/srid/emanote-template/pull/20

**Comment by sellout** [comment]
Perhaps related? https://garnix.io/build/GgbNyODg fails, but works for me locally. I _think_ the 126 error code implies that it couldn’t execute the scripts?

**Comment by jkarni** [comment]
@srid so the solution was to *either* have an explicit input in the dependency, *or* have the dependency be an input where `flake` is `false`? I guess you can't use a `follows` because there (officially) isn't a nixpkgs input?

**Comment by jkarni** [comment]
@sellout can you try using a non-registry (e.g., github) url [here](https://github.com/sellout/bash-strict-mode/blob/main/flake.nix#L74)? It's a bit surprising that the error is what you see instead of something more informative, but if this is the problem, hopefully the idea @srid suggested of having garnix explicitly set an empty registry will help.

**Comment by sellout** [comment]
Ah, thanks. I was a bit confused by the earlier discussion, and since I had a `url` attr, I glossed over the fact that it was from the registry. So, I changed that, but I get the same result. I’m going to try it on another machine see if I can replicate the failure somewhere else.

**Comment by sellout** [comment]
My apologies – I ran this on a different machine and can replicate the failure. I’ll solve it there. Thanks!

**Comment by jkarni** [comment]
I set the registry to be empty, so hopefully the error message is nicer now. Closing, but feel free to reopen if it's not solved.
