### ISSUE TITLE
Build home-manager configurations that are declared in flake.nix files

### ISSUE THREAD

**Issue by greg-hellings** [garnix-io/issues#24]
The vast majority of my user space software gets installed into shared `homeConfigurations.*` targets in my flake.nix file. Even more so than my system configuration, the homeConfigurations bit gets shared between all my systems. I have gui and non-gui targets and that's about it.

I've tried adding two of the homeConfigurations targets to my garnix.yaml file to enable building them, but they aren't built. The app doesn't give any output about not finding particular targets, as best I can tell, so I don't know why it's not building them. I also haven't seen any information about building home manager configurations in the garnix docs.

**Comment by jkarni** [comment]
Currently we only build `nixosConfigurations`, `packages`, `checks`, and `devShells`. I'll add `homeConfigurations`! In the meantime, you could maybe re-expose them under `packages` (I guess the `.config.system.build.toplevel`if `homeConfigurations` is like `nixosConfigurations`)?

**Comment by greg-hellings** [comment]
Yes, it's very similar but the package path is shorter. I have defined

```
homeConfigurations = {
     x86_64-gui = ...
     x86_64-nogui = ...
}
```

I then skip the home-manager rebuild script and instead directly nix build `homeConfigurations.x86_64-gui.activationPackage` and run the script.

**Comment by gvolpe** [comment]
Would love native support for `homeConfigurations` as well. Right now, the workaround is to add `homeConfigurations.host.activationPackage` to `packages.${system}.home-host`, but this requires `--allow-import-from-derivation` for `nix flake show`.

Would also love a badge to replace the GHA ones, as per #45 request :) 

Keep up the great work!

**Comment by soenkehahn** [comment]
For reference: https://github.com/nix-community/home-manager

**Comment by sellout** [comment]
This has now been deployed. `homeConfigurations.*` are now built by default without a garnix.yaml, same as `nixosConfigurations`.

Evidence:
![Screenshot 2023-07-20 at 14 32 49](https://github.com/garnix-io/issues/assets/33031/970e5a3c-9c04-473d-a21b-4e7714141550)

**Comment by greg-hellings** [comment]
Brilliant! Newer versions of home-manager allow them to be directly included in the nixosConfiguration/darwinConfiguration but certainly not everyone is going to use that in every situation. Thanks for getting this working!
