### ISSUE TITLE
aarch64-darwin builds are stuck for 24+ hours

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#34]
Example job still in process for ~24h: 
- https://github.com/EmaApps/emanote/runs/9180488778 
- https://garnix.io/build/V9M2Vxkg

See the CI status in https://github.com/EmaApps/emanote/commits/master 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/3998/198886509-cb09cd2c-57a2-4e3e-b5d4-8ec2027ab03a.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/3998/198886524-8b481404-2662-4f31-8ed1-a3dde3fdeafa.png">

**Comment by jkarni** [comment]
It should be working now (and those builds are finished). Though making sure this doesn't ever happen again will take a bit more work.
