### ISSUE TITLE
Dealing with private flake inputs

### ISSUE THREAD

**Issue by robx** [garnix-io/issues#35]
Currently, a flake with an input from a private github repo, as in

```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.05";
    puzzledb.url = "git+ssh://git@github.com:/robx/puzzledb-mirror.git?ref=nix";
...
```

fails to build on `garnix` with

```
Command 'nix eval .#nixosConfigurations --apply builtins.attrNames --json' failed with exit code 1. Stderr:
error: 'git+ssh://git@github.com:/robx/puzzledb-mirror.git?ref=nix' is not a valid URL
```

It's unclear to me whether that could/should be made to work as is; some documented way to allow building flakes that depend on private flakes via garnix would be nice though.

Suggestion from the [discord thread](https://discord.com/channels/960235377506025542/1037689040050339912) is to change the flake to reference the private input with a `https://` URL using a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

**Comment by gvolpe** [comment]
@jkarni any thoughts on this? On Github Actions, we can configure Nix to use a token as follows:

```ini
access-tokens = github.com=${{ GITHUB_TOKEN }}
```

Is there any under-documented workaround we can use with Garnix nowadays?

**Comment by jkarni** [comment]
Not currently (though maybe there is an under-documented nix feature for
this - i.e., including the token in `inputs.url` in some way). But I should
have some time to look into deploying a fix in a couple of days.

**Comment by gvolpe** [comment]
Hey @jkarni , congrats on the funding and getting Greg onboard! 🚀 

You mentioned [private inputs](https://garnix.io/blog/september-4-2023-release-notes#private-inputs) in your last blog post. Until that documentation is written, is there any example repo I can look at in the meantime? 🙏🏽 😃

**Comment by jkarni** [comment]
This is finally deployed: https://garnix.io/docs/private_inputs
