### ISSUE TITLE
`error: attribute 'packages.x86_64-linux.packages' is unexpectedly missing`

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#36]
I got this error all of sudden on Emanote:

https://github.com/EmaApps/emanote/runs/9443800979

The change itself was a trivial one: https://github.com/EmaApps/emanote/commit/ea28b6bb8fa26fca102d227b71c700b8956cef97

**Comment by srid** [comment]
Seems to be a non-transient issue, as the commit I just tested produced the same error:

https://github.com/EmaApps/emanote/runs/9451187554

**Comment by jkarni** [comment]
I upgrade the `nix` version (it's now 2.9.1), which seems to be the cause of the issue.  @mlyxshi reported this issue last night in the discord channel; it's still unclear whether it's reproducible or not.

 The error is throw [here](https://github.com/NixOS/nix/blob/master/src/libexpr/eval-cache.cc#L391), but I have no insight yet as to why. The incorrect attribute path seems relevant, as does the fact that all it's always all but one builds which fail. I'm inclined to think there's intermediate inconsistent state in the eval cache that's being observer by the other threads. 

I'll try switching to a later `nix` soon. If that doesn't work, I guess it's back to 2.5

**Comment by srid** [comment]
FWIW, my Nix version is 2.11.0 (both on Linux and darwin)

**Comment by jkarni** [comment]
Upgraded to 2.11 (except on Mac). Let me know if that helps!

**Comment by srid** [comment]
It worked, even on aarch64-darwin!

https://github.com/EmaApps/emanote/runs/9452370897

**Comment by jkarni** [comment]
Great! (And I should keep a list of all public projects with a reported failure on a commit, and just add that to the test cases...)

**Comment by mlyxshi** [comment]
Solved
