### ISSUE TITLE
Garnix seemed to stop noticing new pushes to one of my repos

### ISSUE THREAD

**Issue by league** [garnix-io/issues#38]
Hey team. I've been using garnix on my fork of the notmuch mail indexer: [github:league/notmuch](https://github.com/league/notmuch/commits/sort) and the most recent commits don't show the yellow dot, and don't appear in my dashboard on garnix.io. The repo is still enabled in garnix app, as far as I can tell.

However, there is something possibly suspicious further down that commit log. A commit from 14 October appears to have its build still in-progress (yellow dot).  I don't know why it didn't time out, nor whether it would delay recognition of subsequent pushes. The [page for that build](https://garnix.io/build/7gLRQdRB) just says "Waiting for logs."

Thanks so much, garnix is great.

**Comment by jkarni** [comment]
I am indeed seeing this - on *some* repos. It's very mysterious why though - it's not related to the stuck build. In fact, it seems like the webhook Github is sending have recently started being rejected (sometimes) with a 400.

I'll take a look later today and report back. Sorry for this!

(And thanks for the encouraging words!)

**Comment by jkarni** [comment]
Can you try now?

**Comment by league** [comment]
Yes, that shows the build starting!  (Should succeed, because I ran it locally already.)

**Comment by jkarni** [comment]
There's still something wrong. I have an idea for what it is. I hope to have a fix tomorrow.

**Comment by jkarni** [comment]
It turned out there were two issues with libraries behaving in surprising ways, but I think everything should be good now! Closing, but if there's still an issue, please re-open!
