### ISSUE TITLE
garnix not running on PR enabling Garnix

### ISSUE THREAD

**Issue by Gabriella439** [garnix-io/issues#39]
Specifically, this PR: https://github.com/Gabriella439/grace/pull/45

I double-checked that I enabled Garnix for that repository in my GitHub application settings.

I also checked the logs on garnix.io and didn't see any logs related to that repository

**Comment by jkarni** [comment]
Could you try again? We had some issues that were hopefully solved
yesterday.

**Comment by Gabriella439** [comment]
Thank you!  It's working now 😊
