### ISSUE TITLE
blog needs an RSS/Atom feed

### ISSUE THREAD

**Issue by haroldcarr** [garnix-io/issues#40]
Does your blog have a feed?
My feedreader can't find it.
If you don't have one, please consider adding one.

**Comment by alexdavid** [comment]
We've added an [RSS feed for the garnix blog](https://garnix.io/feed.xml). Feel free to re-open if there are any issues with it!

**Comment by haroldcarr** [comment]
My feed reader was able to successfully use the feed.  Thanks!

That said, when I enter `https://garnix.io/feed.xml` into the browser, it complains:
```
This page contains the following errors:
error on line 2 at column 14: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.
```

**Comment by pbsds** [comment]
When i click an entry in the feed i'm taken to an address like `https://garnix.io/announcing-garn`, which likely should be `https://garnix.io/blog/announcing-garn`

**Comment by alexdavid** [comment]
Thanks for the reports! Both of these issues have been fixed.
