### ISSUE TITLE
Garnix doesn't build pull requests from remote repositories?

### ISSUE THREAD

**Issue by Gabriella439** [garnix-io/issues#41]
I'm actually not sure if that's what is happening here, but I noticed that Garnix wasn't building this PR:

https://github.com/Gabriella439/nix-diff/pull/64

… and I'm guessing that the reason why is because the PR's branch from another repository

**Comment by jkarni** [comment]
Yeah, garnix only builds commits in the enabled repo. I'll take a look at
extending it for external repos (though next week at the earliest).

**Comment by jkarni** [comment]
There's [currently no way](https://github.com/orgs/community/discussions/24622) of extending automatic check suites event to these cases, so I'll extend the garnix app permission to include read access to pull request events.

**Comment by jkarni** [comment]
This is now fixed, closing. Feel free to reopen if you encounter issues.
