### ISSUE TITLE
flake in non-standard location

### ISSUE THREAD

**Issue by Mic92** [garnix-io/issues#46]
In some projects one might be not allowed a flake in the toplevel directory (i.e. political/policy reasons).
In our particular project we don't want to use the flake in the toplevel directory since we use unpinned nixpkgs.
Therefore it would be cool if we could specify in garnix.toml an alternative directory.

**Comment by sellout** [comment]
Duplicate of #27.

**Comment by jkarni** [comment]
Closing in favor of #27
