### ISSUE TITLE
Sort job names

### ISSUE THREAD

**Issue by t4ccer** [garnix-io/issues#51]
When building the same project multiple times, each time jobs are ordered differently (see attachment). It would be more convenient to have them in fix (maybe alphabetical) order

![garnix-job-order](https://user-images.githubusercontent.com/64430288/211357570-fd1e669b-c0c3-4c56-9283-b345451c7524.png)

**Comment by jkarni** [comment]
Done! Thanks for the suggestion!

**Comment by jkarni** [comment]
Had to rollback the deploy for different reasons. Will update this issue when I redeploy.
