### ISSUE TITLE
How to restart a build?

### ISSUE THREAD

**Issue by Gabriella439** [garnix-io/issues#52]
I got an Garnix-related error on this PR:

https://github.com/Gabriella439/foldl/pull/188/checks?check_run_id=10504123078

… but I wasn't sure how to restart the build

**Comment by jkarni** [comment]
You can't currently (short of amending the commit), but the fix is simple.
Hopefully tomorrow or day after I'll have it fixed.

**Comment by jkarni** [comment]
This is done. - just click on the `re-run` buttons in GitHub. 

Closing, but feel free to reopen if something is still wrong.
