### ISSUE TITLE
"derivation '...' requires non-existent output '...'"

### ISSUE THREAD

**Issue by zhaofengli** [garnix-io/issues#53]
Looks like the Nix version used on Garnix is still affected by https://github.com/NixOS/nix/issues/6572 which was fixed in https://github.com/NixOS/nix/pull/7283. Is it possible for the Nix version on Garnix to be updated? Thanks for such an amazing service!

Example failure: https://garnix.io/build/vBV7ejZ9

**Comment by jkarni** [comment]
Upgraded to nix 2.13.2. Closing, but if this isn't fixed, please let me know!

**Comment by jkarni** [comment]
Had to rollback the deploy for different reasons. Will update this issue when I redeploy.

**Comment by jkarni** [comment]
Sorry, this is stuck on [this issue](https://github.com/aristanetworks/nix-serve-ng/issues/22), which I haven't had any time to fix.
