### ISSUE TITLE
check suite statuses are not reported to github

### ISSUE THREAD

**Issue by getchoo** [garnix-io/issues#64]
hi again! this is the only other issue i've come across with garnix so far, where i've noticed that when querying the github api for the commit status (using the regular [status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#get-the-combined-status-for-a-specific-reference) endpoint), the state is reported as `pending` and the `statuses` property is left blank. this is comparison to hercules-ci (and other ci solutions), that allow you to check the state and list other information about each individual status.

a reference for this is in https://github.com/getchoo/flake/commit/c71a2c41f4e98b394bebe738d1f582c440d5337e with hercules-ci statuses being reported, in comparison to https://github.com/getchoo/flake/commit/3716419055f11a80c3bab92de343075c15f84be1 where the garnix check suite is completed but the api response is never updated.

<details>
  <summary>api response examples</summary>
  <br \>
  <p>hercules-ci in <code>c71a2c4</code></p>
  <img src=https://github.com/garnix-io/issues/assets/48872998/ba108fbb-1d49-492f-b8a7-eaff0950ac65 />
  <br \>
  <br \>
  <p>garnix in <code>3716419</code></p>
  <img src=https://github.com/garnix-io/issues/assets/48872998/2deb3f0e-7dba-41e6-9a18-757ba1be460d />
</details>

**Comment by jkarni** [comment]
Instead of the `/status` endpoint, can you use `/check-runs` and `/check-suites`? See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#types-of-status-checks-on-github) for a bit on the differences.

If you just need the `garnix` check-suite, you can do something like:

```
gh api "/repos/<org>/<repo>/commits/<commit>/check-suites" | jq '.check_suites[] | select (.app.slug == "garnix-ci")'
```

(And sorry for the long delay!)

**Comment by jkarni** [comment]
(Closing this because of the answer above, but if that doesn't feel satisfactory, I'm happy to reopen.)
