### ISSUE TITLE
Fix HTML background color issue

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#67]
@sellout's view of garnix.io has a gray, rather than white, background. Fix this. It's probably as simple as explicitly setting the body background to white.

**Comment by soenkehahn** [comment]
This is in review, but I'm not sure what to review here. Also couldn't find a PR for this.

**Comment by sellout** [comment]
This is fixed now.

**Comment by soenkehahn** [comment]
Thank you! :)
