### ISSUE TITLE
Garnix stalls during evaluation

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#68]
Sometimes we get builds that run indefinitely during evaluation ("Build starting"). Still unclear exactly when this happens, so if anyone has more reproductions, please share here!

**Comment by jkarni** [comment]
These failures also sometimes happen transiently, which is a know issue. But this issue is specifically about failures that don't get fixed with another force push of an empty commit (or a rerun)

**Comment by sellout** [comment]
This has been resolved.
