### ISSUE TITLE
Failed builds, no information why

### ISSUE THREAD

**Issue by kamadorueda** [garnix-io/issues#7]
Log: https://garnix.io/build/kamadorueda/alejandra/511c3f6a88b6964e1496fb6f441f4ae5e58bd3ea/alejandra-x86_64-apple-darwin

```
repo: kamadorueda/alejandra
commit: 511c3f6a88b6964e1496fb6f441f4ae5e58bd3ea
package: alejandra-x86_64-apple-darwin
status: Failure
started at: 2022-03-04T02:29:36.266444Z
finished at: 2022-03-04T02:29:36.8271Z
Logs
No logs available
```

Of course I suspect it is because darwin is an unsupported system 

This issue is about that I don't see information in the website indicating why, there are no logs, just an anonymous 'failure'

**Comment by jkarni** [comment]
There are many versions of this that have been fixed. Closing, but if you have another example, do open another issue!
