### ISSUE TITLE
recursive evaluation of homeConfigurations

### ISSUE THREAD

**Issue by getchoo** [garnix-io/issues#70]
currently, garnix seems to only support a flat layout of the `homeConfigurations` attribute (i.e., `homeConfigurations."user@home"`) after it's introduction in #24. i think a good addition to this would be to also evaluate nested attributes such as `homeConfigurations.x86_64-linux.user`, since that is used commonly for standalone, non host specific home configurations.

an example an be found at [this](https://github.com/getchoo/flake/pull/108/commits/a6988ca2ccf4746fcaacc591e0b61643ec1555ab) commit, where i specified `homeConfigurations.x86_64-linux.*`, but it wasn't evaluated in the resulting [run](https://github.com/getchoo/flake/runs/15411688682). a workaround i found (that doesn't require flattening the homeConfigurations attribute) was to export them as packages like so:

```nix
packages = forAllSystems (sys: builtins.mapAttrs (_: v: v.activationPackage) self.homeConfigurations.${sys}));
```

however this can break things like `nix flake show` due to the common use of [IFD](https://nixos.wiki/wiki/Import_From_Derivation) in home configurations - plus it's a bit counterintuitive

**Comment by sellout** [comment]
I think garnix is unlikely to support something like this until at least home-manager does.
```bash
$ home-manager build --flake github:getchoo/flake#x86_64-linux.seth
error: flake 'github:getchoo/flake' does not provide attribute 'packages.x86_64-linux.homeConfigurations."x86_64-linux.seth".activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations."x86_64-linux.seth".activationPackage' or 'homeConfigurations."x86_64-linux.seth".activationPackage'
```
and it looks like `home-manager` is following `nixos-rebuild`’s lead in parsing `.`-containing fragments as a single attribute name:
```bash
$ nixos-rebuild build --flake github:getchoo/flake#x86_64-linux.seth
building the system configuration...
error: flake 'github:getchoo/flake' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."x86_64-linux.seth".config.system.build.toplevel', 'legacyPackages.x86_64-linux.nixosConfigurations."x86_64-linux.seth".config.system.build.toplevel' or 'nixosConfigurations."x86_64-linux.seth".config.system.build.toplevel'
```
In general, flakes seem to discourage outputs that don’t exist at precisely the expected layer. E.g., you also can’t nest `nixosConfigurations` (the most similar “official” output) an extra layer, or `packages`, or anything else.

I too have wanted to put derivations in non-standard places, or make other adjustments. But garnix probably isn’t going to be the place to initiate that. If there are issues for this against home-manager or NixOS already, then it’d be good to reference them here so they can be tracked, and so other supporters can boost those issues.

**Comment by sellout** [comment]
Closing this until something similar is supported in more foundational tools.

**Comment by sellout** [comment]
Sorry, closed with wrong status.
