### ISSUE TITLE
No way to download logs

### ISSUE THREAD

**Issue by 9999years** [garnix-io/issues#72]
Currently, there's no way to download the build logs as a text file.

**Comment by jkarni** [comment]
I'm wondering what the best UX for this is. Some options:

- 1) A `Copy` button next to the logs that copies them in their entirety to the clipboard
- 2) A `Raw` button that goes to a URL with content-type of plaintext of the logs
- 3) A `Download` button that's the same as 2, but automatically downloads
- 4) A `garnix` CLI that you can authenticate into, and which has a `logs` command

I personally am partial to 4, but am curious to hear whether that fits your use case!

**Comment by alexdavid** [comment]
We've implemented idea 2, which seems to be the most flexible of 1-3 (you can navigate to that page and then copy the text, view it, or easily download it. The download button is next to the "Logs" header on a build page.
