### ISSUE TITLE
No way to re-run builds

### ISSUE THREAD

**Issue by 9999years** [garnix-io/issues#73]
There is a re-run button for failed builds, but it doesn't seem to do anything.

I'd also like the ability to re-run successful builds to diagnose flaky errors.

**Comment by jkarni** [comment]
Re-run *does* work for failed builds. But we only inform github that the rerun has started *after* cloning the repo again, and evaluating the flake. This means it can take a few seconds to appear there, which is less than ideal. 

For successful builds, it's true that nix will reuse the cache. If we simply allow force re-running, the old logs will be lost, which might make diagnosing these errors harder. Maybe the best UX for doing this is different than just re-running - maybe a more full-fledged feature. 

Do you mind if I split this into two tasks (one for nicer failed re-run UI, and one for help diagnosing flaky builds)?

**Comment by 9999years** [comment]
Yes, go for it!

**Comment by 9999years** [comment]
Split this into #79 and #80.
