### ISSUE TITLE
View logs for dependency builds

### ISSUE THREAD

**Issue by 9999years** [garnix-io/issues#74]
The logs for dependency derivations disappear along with the "xxx derivations will be built" output when the final derivation is built. Those logs are useful (particularly for debugging caching) and I'd like to be able to view them.

**Comment by jkarni** [comment]
This would be very nice! I think in particular we should allow navigating through logs of the dependencies, sort of like nix-tree.

**Comment by jkarni** [comment]
This is now done. They are also kept in separate folds so you can more easily pick them. 

Closing, but feel free to reopen if that doesn't sound right.
