### ISSUE TITLE
502 errors

### ISSUE THREAD

**Issue by Gabriella439** [garnix-io/issues#75]
There seems to be a 502 error fetching a cache product here:

https://github.com/MercuryTechnologies/hlint-plugin/pull/1/checks?check_run_id=16423031460

**Comment by jkarni** [comment]
Yeah, we just noticed this too. Looking into it!

**Comment by soenkehahn** [comment]
Thanks for the quick report! It should be fixed now. Please re-open if you're still seeing this on restarted builds.

**Comment by Gabriella439** [comment]
thank you!!
