### ISSUE TITLE
Cannot click when pkg name is long

### ISSUE THREAD

**Issue by kamadorueda** [garnix-io/issues#8]
I cannot click on alejandra-i686's success, but I can click on the running below and success above

I suppose the dots are overlapping with the button:

![image](https://user-images.githubusercontent.com/47480384/156691709-6b7ced06-7330-4c02-8825-94b75b7a2130.png)

**Comment by jkarni** [comment]
This should be a bit better now that builds are grouped by commit (and so lines are shorter), but the underlying problem hasn't been fixed, so I'm leaving this open.

**Comment by jkarni** [comment]
The package names also now wrap to not be on top of the links.
