### ISSUE TITLE
homeConfigs fail to build on aarch64-linux

### ISSUE THREAD

**Issue by sellout** [garnix-io/issues#81]
For example, https://github.com/sellout/dotfiles/runs/18143129706 fails with
```
error: Unsupported system: aarch64-linux
```

But homeConfigs succeed on both x86_64-linux and aarch64-darwin (so it seems homeConfigs are being dispatched to appropriate build machines in at least some cases).

And they _used to_ succeed on aarch64-linux, too – see https://github.com/sellout/dhall-path/runs/16740585742

**Comment by r-vdp** [comment]
It actually seems that several packages in your home config just aren't available for aarch64-linux in the nixpkgs version that you're using:

```nix
nix-repl> :lf github:sellout/dotfiles/eeb74ee
nix-repl> :lf nixpkgs
nix-repl> let system = "aarch64-linux"; in map (drv: (builtins.tryEval drv.name).value) (lib.filter (drv: ! lib.meta.availableOn (lib.systems.elaborate system) drv) homeConfigurations."${system}-dotfiles-example".config.home.packages)
[ false "chrysalis-0.12.0-binary" "cider-1.6.1" "eagle-9.6.2" "ferdium-6.2.6" "keybase-gui-6.0.2" "signal-desktop-6.32.0" "tor-browser-bundle-bin-13.0" "firefox-bin-118.0.2" ]
```

So AFAICT, this is a normal eval error.

The first element of the list seems to be a drv without a `name` attribute.

**Comment by sellout** [comment]
Thanks! I was thrown off because it wasn’t the usual
```
error: Package ‘chrysalis-0.12.0-binary’ in /nix/store/…-source/pkgs/applications/misc/chrysalis/default.nix:36 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.
```
But it looks like the `false` refers to Zoom, which [relies on `system` to create the `version`](https://github.com/NixOS/nixpkgs/blob/16cfcd2ef6919e6e34ef34b460ad4fcbf6bade07/pkgs/applications/networking/instant-messengers/zoom-us/default.nix#L118) and otherwise throws its custom (uninformative) error message.

If Zoom hadn’t been the first thing in the list, it would have been apparent, so I opened an upstream issue: NixOS/nixpkgs#264612
