### ISSUE TITLE
Builds fail, but eventually succeed with multiple re-runs

### ISSUE THREAD

**Issue by devusb** [garnix-io/issues#84]
I have three `nixosConfiguration` builds that began failing yesterday -- re-running will eventually make them succeed; typically the best way to get a success is to run each job individually rather than all at once. There is no output in either log when there is a failure.

Failed build example: https://garnix.io/build/pgEzW8E0

`garnix.yaml` https://github.com/devusb/nix-config/blob/main/garnix.yaml

**Comment by devusb** [comment]
Seems to be working now.

**Comment by soenkehahn** [comment]
Yeah, we had some degradation in builds, which should be fixed now. Thanks for reporting!

**Comment by devusb** [comment]
Glad to know it wasn't me :)

**Comment by devusb** [comment]
@soenkehahn I’m getting failures again — just wanting to make sure this isn’t something on my side. 

Recent failed build: https://github.com/devusb/nix-config/pull/47/checks?check_run_id=19922509649

**Comment by jkarni** [comment]
I think this is fixed, but feel free to reopen!
