### ISSUE TITLE
Add "Everything worked" meta-check

### ISSUE THREAD

**Issue by emanueljg** [garnix-io/issues#87]
I propose an "Everything worked" meta-check to be added to Garnix.

**How it would work**
If all Garnix builds are built successfully, this check would report success too. If at least one build would fail, this check would report failure.

**Rationale**
Currently, if you want to configure a branch ruleset to need all Garnix status checks to pass, you need to add every single output build 1 by 1. This is not only tiresome since even simple flakes can easily hit 10+ different outputs being built, but also prone to human error as you have to remember to add a new output to the required status checks every time.

Side-note: an adjacent feature to this would be to have such a meta-check for each output "type"; all nixosConfigurations, all packages, all `x86_64-linux` packages, etc.

**Comment by jkarni** [comment]
We implemented this as a "Meta check". Closing, but let us know if we missed anything!
