### ISSUE TITLE
can't sign up

### ISSUE THREAD

**Issue by bwkam** [garnix-io/issues#89]
![image](https://github.com/garnix-io/issues/assets/91009118/8c7bd781-9eb3-402b-a643-b07e04a2e227)
nothing happens when I click that, there is a nextjs error in the console though:
```
Uncaught TypeError: e.call is not a function
```

edit: this behavior occurs on firefox, works fine on chrome
edit 2: It's because ublock origin, disabling it fixed it.

**Comment by alexdavid** [comment]
Fix has been deployed, thanks for reporting!
