### ISSUE TITLE
Consider placing docs in the main page

### ISSUE THREAD

**Issue by kamadorueda** [garnix-io/issues#9]
I discovered the docs by typing https://garnix.io/docs in the browser, but it's not linked to from the main page, and therefore not easily discoverable

**Comment by jkarni** [comment]
They're now in the dropdown for logged in users. They're still in quite a sorry state, so I don't know how useful linking to them is for people who are trying to figure out what garnix is, and so I didn't link to them when you're not logged in yet. (Also, I'm going to have to think more about the design in general.)

**Comment by jkarni** [comment]
Done.
