### ISSUE TITLE
404 on build of a public repo's PR

### ISSUE THREAD

**Issue by develop7** [garnix-io/issues#91]
Repro:

1. Do a PR to a public repository using Garnix CI (https://github.com/iand675/hs-opentelemetry/pull/114)
2. Go to "Checks" (https://github.com/iand675/hs-opentelemetry/pull/114/checks) then an URL on the "View more details on Garnix CI" link, which leads to https://garnix.io/commit/ab36cdd75c58c7aa1eb1816feb8b6c3e280c0ff1
3. Click any of the build jobs, e.g. https://garnix.io/build/D07eGxP9

Expected: well, the job page, featuring, hopefully, job log

Instead: 404 page saying 

> Uh oh! No build matching that description could be found. Either it doesn't exist, or you don't have access to it.

**Comment by jkarni** [comment]
This is fixed now, closing. And thanks for the report!
