### ISSUE TITLE
Persistence settings are incorrect in docs

### ISSUE THREAD

**Issue by gvolpe** [garnix-io/issues#96]
Hey all, just a tiny mistake I noticed in the docs: https://garnix.io/docs/hosting/persistence

It should be `garnix.server.persistence.enable` and `garnix.server.persistence.name` instead of the current `garnix.persistence.*`. 

PS: I would submit a PR but don't think the docs repo is public?

**Comment by jkarni** [comment]
Thanks a lot for the report - we'll deploy a fix in a bit! Making the docs public is a great idea, but might be a bit longer.

I also saw https://gvolpe.com/blog/nixos-server/ - thanks a lot for the kind words! Is it okay to post is to places?

**Comment by gvolpe** [comment]
> I also saw https://gvolpe.com/blog/nixos-server/ - thanks a lot for the kind words! Is it okay to post is to places?

Thank you! Feel free to share :)
